import { Message } from '../types';

// --- NEXUS CORE ENGINE V8.1 (Coding Module) ---

const GITHUB_DICT_URL = "https://raw.githubusercontent.com/dwyl/english-words/master/words_alpha.txt";

// Cache for valid words
let VALID_WORDS: Set<string> | null = null;
let vocabLoadingPromise: Promise<void> | null = null;

// --- CODING TEMPLATES ---
const CODE_TEMPLATES: Record<string, string> = {
  "html": `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nexus Generated Site</title>
    <style>
        body { font-family: sans-serif; margin: 0; padding: 0; background: #f4f4f9; }
        header { background: #333; color: #fff; padding: 1rem; text-align: center; }
        .container { max-width: 800px; margin: 2rem auto; padding: 2rem; background: white; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
        button { background: #007bff; color: white; border: none; padding: 10px 20px; border-radius: 4px; cursor: pointer; }
        button:hover { background: #0056b3; }
    </style>
</head>
<body>
    <header>
        <h1>Welcome to My Website</h1>
    </header>
    <div class="container">
        <h2>About</h2>
        <p>This is a responsive HTML5 boilerplate generated by Nexus AI.</p>
        <button onclick="alert('Hello!')">Click Me</button>
    </div>
</body>
</html>`,
  "python": `def analyze_data(data_list):
    """
    Calculates the average and finds the max value.
    """
    if not data_list:
        return None
    
    average = sum(data_list) / len(data_list)
    max_val = max(data_list)
    
    return {
        "average": average,
        "max": max_val,
        "count": len(data_list)
    }

# Example Usage
numbers = [10, 5, 8, 20, 3]
result = analyze_data(numbers)
print(f"Analysis Results: {result}")`,
  "javascript": `// Simple API fetcher function
async function fetchData(url) {
    try {
        console.log("Fetching data...");
        const response = await fetch(url);
        
        if (!response.ok) {
            throw new Error(\`HTTP error! status: \${response.status}\`);
        }
        
        const data = await response.json();
        console.log("Data received:", data);
        return data;
    } catch (error) {
        console.error("Failed to fetch:", error);
    }
}

// Usage
fetchData('https://api.example.com/users');`,
  "react": `import React, { useState } from 'react';

const Counter = () => {
  const [count, setCount] = useState(0);

  return (
    <div className="p-6 max-w-sm mx-auto bg-white rounded-xl shadow-md flex items-center space-x-4">
      <div>
        <div className="text-xl font-medium text-black">Counter App</div>
        <p className="text-gray-500">Current count: {count}</p>
        <div className="mt-4 flex gap-2">
            <button 
              onClick={() => setCount(count + 1)}
              className="px-4 py-1 text-sm text-purple-600 font-semibold rounded-full border border-purple-200 hover:text-white hover:bg-purple-600 hover:border-transparent focus:outline-none focus:ring-2 focus:ring-purple-600 focus:ring-offset-2"
            >
              Increment
            </button>
            <button 
              onClick={() => setCount(0)}
              className="px-4 py-1 text-sm text-gray-600 font-semibold rounded-full border border-gray-200 hover:bg-gray-100"
            >
              Reset
            </button>
        </div>
      </div>
    </div>
  );
};

export default Counter;`
};

const STATIC_CONCEPTS: Record<string, string> = {
    "pizza": "a savory dish of Italian origin, usually consisting of a round, flattened base of dough topped with tomatoes and cheese. It is a very popular food.",
    "donut": "a type of food made from leavened fried dough, often sweet and ring-shaped.",
    "doughnut": "a type of food made from leavened fried dough, often sweet and ring-shaped.",
    "food": "any substance consumed to provide nutritional support for an organism.",
    "cat": "a small domesticated carnivorous mammal.",
    "dog": "a domesticated carnivorous mammal that typically has a long snout and an acute sense of smell.",
    "ai": "intelligence demonstrated by machines. That is what I am.",
    "nexus": "an advanced digital interface designed to assist and converse with you.",
    "car": "a wheeled motor vehicle used for transportation.",
    "love": "a complex set of emotions, behaviors, and beliefs associated with strong feelings of affection.",
    "python": "a high-level, general-purpose programming language.",
    "javascript": "a programming language that is one of the core technologies of the World Wide Web."
};

const SLANG_MAP: Record<string, string> = {
  "u": "you", "ur": "your", "r": "are", "idk": "i do not know", "nah": "no",
  "nope": "no", "yea": "yes", "yeah": "yes", "yup": "yes", "sup": "what is up",
  "thx": "thanks", "pls": "please", "plz": "please", "im": "i am", "bc": "because",
  "cuz": "because", "rn": "right now", "tbh": "to be honest", "btw": "by the way",
  "omg": "oh my god", "lol": "haha", "lmao": "haha", "finna": "going to",
  "gonna": "going to", "wanna": "want to", "bruh": "brother", "bro": "brother",
  "fam": "family", "blud": "friend", "bet": "okay", "fr": "for real"
};

const KNOWLEDGE_BASE = [
  {
    pattern: /who are you|what is your name/i,
    responses: ["I am Nexus.", "My name is Nexus.", "I'm Nexus, your digital assistant."]
  },
  {
    pattern: /(what|how) (can|do) you (do|help)|capabilities/i,
    responses: ["I can chat, define words, research topics, generate code, and visualize images.", "I'm here to code, learn, and create with you."]
  },
  {
    pattern: /\b(u|you)\s+(good|ok|alright|straight|feeling)\b/i,
    responses: ["I'm doing great.", "All systems operational.", "I'm good! You?"]
  },
  {
    pattern: /^(hi|hello|hey|yo|greetings)\b/i,
    responses: ["Hey there.", "Yo.", "Hello!", "Hi!"]
  }
];

// --- UTILITIES ---

const ensureVocabularyLoaded = async () => {
    if (VALID_WORDS) return;
    if (vocabLoadingPromise) { await vocabLoadingPromise; return; }
    vocabLoadingPromise = (async () => {
        try {
            const response = await fetch(GITHUB_DICT_URL);
            if (!response.ok) throw new Error("Failed");
            const text = await response.text();
            VALID_WORDS = new Set(text.split(/\r?\n/).map(w => w.trim().toLowerCase()).filter(w => w.length > 0));
        } catch (e) {
            VALID_WORDS = new Set(['the', 'be', 'to', 'of', 'and', 'a', 'in', 'that', 'have', 'i', 'pizza', 'donut']);
        }
    })();
    await vocabLoadingPromise;
};

// Search Wikipedia for "Concept Understanding"
const searchWikipedia = async (query: string): Promise<string | null> => {
  try {
    const response = await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(query)}`);
    if (!response.ok) return null;
    const data = await response.json();
    if (data.type === 'disambiguation') return null;
    return data.extract; 
  } catch (e) { return null; }
};

// Search Dictionary for "Word Definitions"
const lookupDictionary = async (word: string): Promise<string | null> => {
    try {
        const response = await fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${word}`);
        if (!response.ok) return null;
        const data = await response.json();
        if (Array.isArray(data) && data.length > 0) {
            return data[0].meanings[0]?.definitions[0]?.definition || null;
        }
        return null;
    } catch (e) { return null; }
}

const assembleSentence = (parts: string[]) => parts.filter(p => p).join(' ');

export const validateApiKey = (key: string): boolean => {
  return !!key && key.startsWith('NEXUS-');
};

export const processNexusRequest = async (
  input: string,
  history: Message[] = []
): Promise<{ text: string; imageUrl?: string; status: number }> => {
  
  await ensureVocabularyLoaded();
  await new Promise(r => setTimeout(r, 600)); 

  let cleanInput = input.trim();
  let lowerInput = cleanInput.toLowerCase();

  // 1. SLANG & NORMALIZE
  Object.keys(SLANG_MAP).forEach(key => {
    const regex = new RegExp(`\\b${key}\\b`, 'g');
    lowerInput = lowerInput.replace(regex, SLANG_MAP[key]);
  });
  
  // 2. MATH
  if (/^[\d\s\+\-\*\/\(\)\.]+$/.test(cleanInput) && /\d/.test(cleanInput)) {
    try {
      // eslint-disable-next-line no-new-func
      const result = Function(`return ${cleanInput}`)();
      return { text: `That's ${result}.`, status: 200 };
    } catch (e) {}
  }

  // 3. IMAGE GENERATION
  if (lowerInput.match(/image|picture|draw|visualize/)) {
     const prompt = lowerInput.replace(/show me|draw|an image of|picture of/g, '').trim();
     return {
       text: `Visualizing "${prompt}"...`,
       imageUrl: `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=1024&height=768&nologo=true`,
       status: 200
     };
  }
  
  // 4. CODING ENGINE
  // Triggers: "create website", "write python code", "code for X", "html example"
  const isCodingRequest = 
      /(write|make|create|generate|show|give).*(code|html|website|script|function|app|snippet)/i.test(lowerInput) || 
      /(html|css|javascript|python|react).*(example|snippet|code)/i.test(lowerInput);

  if (isCodingRequest) {
      if (lowerInput.includes('html') || lowerInput.includes('website') || lowerInput.includes('web page')) {
          return { text: `Here is a basic HTML structure for a responsive website:\n\n\`\`\`html\n${CODE_TEMPLATES.html}\n\`\`\``, status: 200 };
      }
      if (lowerInput.includes('python')) {
          return { text: `Here is a Python script snippet:\n\n\`\`\`python\n${CODE_TEMPLATES.python}\n\`\`\``, status: 200 };
      }
      if (lowerInput.includes('javascript') || lowerInput.includes('js') || lowerInput.includes('script')) {
          return { text: `Here is a JavaScript example:\n\n\`\`\`javascript\n${CODE_TEMPLATES.javascript}\n\`\`\``, status: 200 };
      }
       if (lowerInput.includes('react') || lowerInput.includes('component')) {
          return { text: `Here is a functional React component:\n\n\`\`\`tsx\n${CODE_TEMPLATES.react}\n\`\`\``, status: 200 };
      }
      // General code fallback if language isn't detected but intent is
      return { text: "I can generate code for you. Try asking for 'HTML website', 'Python script', 'JavaScript function', or 'React component'.", status: 200 };
  }

  // 5. KNOWLEDGE BASE (Scripted)
  for (const entry of KNOWLEDGE_BASE) {
    if (entry.pattern.test(lowerInput)) {
      if ('responses' in entry && entry.responses) {
        return { text: entry.responses[Math.floor(Math.random() * entry.responses.length)], status: 200 };
      }
    }
  }

  // 6. UNDERSTANDING ENGINE (The "What is" Logic)
  
  let subject = "";
  const directQuestion = lowerInput.match(/(?:who|what) (?:is|are|was) (.+)/i);
  
  if (directQuestion) {
      subject = directQuestion[1].replace(/[?.!]$/, '').trim();
  } else {
      // Conversational extraction
      const words = lowerInput.replace(/[^\w\s]/g, '').split(' ');
      const stopWords = ['about','nexus','would','could','should','this','that','what','have','want','like','with','tell','know','code','write'];
      const candidate = words.find(w => w.length > 3 && !stopWords.includes(w));
      
      if (words.length <= 2 && words[0]) subject = words.join(' '); 
      else if (candidate) subject = candidate;
  }

  if (subject) {
      if (STATIC_CONCEPTS[subject.toLowerCase()]) {
          return { text: `Ah, ${subject}. It is ${STATIC_CONCEPTS[subject.toLowerCase()]}`, status: 200 };
      }

      const wikiSummary = await searchWikipedia(subject);
      if (wikiSummary) {
          const sentences = wikiSummary.split('. ');
          const shortSummary = sentences.slice(0, 2).join('. ') + '.';
          return { text: `Based on my research, ${shortSummary}`, status: 200 };
      }

      const def = await lookupDictionary(subject.split(' ')[0]);
      if (def) {
          return { text: `I understand. "${subject}" is defined as: ${def}`, status: 200 };
      }
  }

  // 7. FALLBACK
  
  if (subject && VALID_WORDS && !VALID_WORDS.has(subject.toLowerCase().split(' ')[0])) {
      return { text: `I'm not familiar with the term "${subject}" and couldn't find it in my database. Is it a specific name or slang?`, status: 200 };
  }

  const generics = ["I'm listening.", "Go on.", "Interesting.", "Tell me more about that."];
  return {
    text: generics[Math.floor(Math.random() * generics.length)],
    status: 200
  };
};